name: Publish ekobol STATIC to public repo

on:
  push:
    branches: [ "main" ]     # hangi branchtan yayınlayacaksan onu yaz
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (opsiyonel) debug için dosyaları listele
      - name: List files
        run: ls -la

      # STATİK NE VARSA KÖKTEN ALIP public repoya /ekobol altına bas
      - name: Deploy to methetech.github.io/ekobol
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          external_repository: methetech/methetech.github.io   # hedef PUBLIC repo
          publish_branch: main                                  # public repo Pages: main/(root)
          publish_dir: .                                        # private repo KÖKÜ (index.html, static/ vs.)
          destination_dir: ekobol                               # URL: /ekobol/
          exclude_assets: |
            .github
            .gitignore
            README.md
            LICENSE
