name: Publish ekobol to public Pages repo

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build   # Çıktın CRA ise build/, Vite ise dist/, Next export ise out/

      - name: Deploy to methetech.github.io/ekobol
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          external_repository: methetech/methetech.github.io
          publish_branch: main
          publish_dir: ./build        # Vite: ./dist  | CRA: ./build | Next: ./out
          destination_dir: ekobol
