name: Publish ekobol to public Pages repo

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci || npm i

      - name: Build
        run: npm run build

      - name: Deploy to methetech.github.io/ekobol
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn --frozen-lockfile
      - run: yarn build
