name: Publish ekobol to public Pages repo

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (Yarn cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install deps
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build    # ÇIKTI klasörün: CRA=build  | Vite=dist  | Next export=out

      - name: Deploy to methetech.github.io/ekobol
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          external_repository: methetech/methetech.github.io
          publish_branch: main
          publish_dir: ./build      # Vite ise ./dist, Next export ise ./out yaz
          destination_dir: ekobol
