name: Publish ekobol to public Pages repo

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci || npm i

      - name: Build
        run: npm run build

      - name: Deploy to methetech.github.io/ekobol
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          external_repository: methetech/methetech.github.io
          publish_branch: main
          publish_dir: ./build      # Vite: ./dist | CRA: ./build | Next export: ./out
          destination_dir: ekobol
